In [ ]:
pip install requests bs4

In [3]:
from bs4 import BeautifulSoup
import requests
res=requests.get("https://addisinsight.net/")
res.status_code

200

In [5]:
print(soup.prettify()[:5000])

<!DOCTYPE html >
<head>
 <meta charset="utf-8"/>
 <script>
  if(navigator.userAgent.match(/MSIE|Internet Explorer/i)||navigator.userAgent.match(/Trident\/7\..*?rv:11/i)){var href=document.location.href;if(!href.match(/[?&]nowprocket/)){if(href.indexOf("?")==-1){if(href.indexOf("#")==-1){document.location.href=href+"?nowprocket=1"}else{document.location.href=href.replace("#","?nowprocket=1#")}}else{if(href.indexOf("#")==-1){document.location.href=href+"&nowprocket=1"}else{document.location.href=href.replace("#","&nowprocket=1#")}}}}
 </script>
 <script>
  (()=>{class RocketLazyLoadScripts{constructor(){this.v="2.0.4",this.userEvents=["keydown","keyup","mousedown","mouseup","mousemove","mouseover","mouseout","touchmove","touchstart","touchend","touchcancel","wheel","click","dblclick","input"],this.attributeEvents=["onblur","onclick","oncontextmenu","ondblclick","onfocus","onmousedown","onmouseenter","onmouseleave","onmousemove","onmouseout","onmouseover","onmouseup","onmousewheel","onscroll","onsubmit"]}async t(){this.i(),this.o(),/iP(ad|hone)/.test(navigator.userAgent)&&this.h(),this.u(),this.l(this),this.m(),this.k(this),this.p(this),this._(),await Promise.all([this.R(),this.L()]),this.lastBreath=Date.now(),this.S(this),this.P(),this.D(),this.O(),this.M(),await this.C(this.delayedScripts.normal),await this.C(this.delayedScripts.defer),await this.C(this.delayedScripts.async),await this.T(),await this.F(),await this.j(),await this.A(),window.dispatchEvent(new Event("rocket-allScriptsLoaded")),this.everythingLoaded=!0,this.lastTouchEnd&&await new Promise(t=>setTimeout(t,500-Date.now()+this.lastTouchEnd)),this.I(),this.H(),this.U(),this.W()}i(){this.CSPIssue=sessionStorage.getItem("rocketCSPIssue"),document.addEventListener("securitypolicyviolation",t=>{this.CSPIssue||"script-src-elem"!==t.violatedDirective||"data"!==t.blockedURI||(this.CSPIssue=!0,sessionStorage.setItem("rocketCSPIssue",!0))},{isRocket:!0})}o(){window.addEventListener("pageshow",t=>{this.persisted=t.persisted,this.realWindowLoadedFired=!0},{isRocket:!0}),window.addEventListener("pagehide",()=>{this.onFirstUserAction=null},{isRocket:!0})}h(){let t;function e(e){t=e}window.addEventListener("touchstart",e,{isRocket:!0}),window.addEventListener("touchend",function i(o){o.changedTouches[0]&&t.changedTouches[0]&&Math.abs(o.changedTouches[0].pageX-t.changedTouches[0].pageX)<10&&Math.abs(o.changedTouches[0].pageY-t.changedTouches[0].pageY)<10&&o.timeStamp-t.timeStamp<200&&(window.removeEventListener("touchstart",e,{isRocket:!0}),window.removeEventListener("touchend",i,{isRocket:!0}),"INPUT"===o.target.tagName&&"text"===o.target.type||(o.target.dispatchEvent(new TouchEvent("touchend",{target:o.target,bubbles:!0})),o.target.dispatchEvent(new MouseEvent("mouseover",{target:o.target,bubbles:!0})),o.target.dispatchEvent(new PointerEvent("click",{target:o.target,bubbles:!0,cancelable:!0,detail:1,clientX:o.changedTouches[0].clientX,clientY:o.changedTouches[0].clientY})),event.preventDefault()))},{isRocket:!0})}q(t){this.userActionTriggered||("mousemove"!==t.type||this.firstMousemoveIgnored?"keyup"===t.type||"mouseover"===t.type||"mouseout"===t.type||(this.userActionTriggered=!0,this.onFirstUserAction&&this.onFirstUserAction()):this.firstMousemoveIgnored=!0),"click"===t.type&&t.preventDefault(),t.stopPropagation(),t.stopImmediatePropagation(),"touchstart"===this.lastEvent&&"touchend"===t.type&&(this.lastTouchEnd=Date.now()),"click"===t.type&&(this.lastTouchEnd=0),this.lastEvent=t.type,t.composedPath&&t.composedPath()[0].getRootNode()instanceof ShadowRoot&&(t.rocketTarget=t.composedPath()[0]),this.savedUserEvents.push(t)}u(){this.savedUserEvents=[],this.userEventHandler=this.q.bind(this),this.userEvents.forEach(t=>window.addEventListener(t,this.userEventHandler,{passive:!1,isRocket:!0})),document.addEventListener("visibilitychange",this.userEventHandler,{isRocket:!0})}U(){this.userEvents.forEach(t=>window.removeEventListener(t,this.userEventHandler,{passive:!1,isRocket:!0})),document.removeEventListener("visibilitychange",this.userEventHandler,{isRocket:!0}),this.savedUserEvents.forEach(t=>{(t.rocketTarget||t.target).dispatchEvent(new window[t.constructor.name](t.type,t))})}m(){const t="return false",e=Array.from(this.attributeEvents,t=>"data-rocket-"+t),i="["+this.attributeEvents.join("],[")+"]",o="[data-rocket-"+this.attributeEvents.join("],[data-rocket-")+"]",s=(e,i,o)=>{o&&o!==t&&(e.setAttribute("data-rocket-"+i,o),e["rocket"+i]=new Function("event",o),e.setAttribute(i,t))};new MutationObserver(t=>{for(const n of t)"attributes"===n.type&&(n.attributeName.startsWith("data-rocket-")||this.everythingLoaded?n.attributeName.startsWith("data-rocket-")&&this.everythingLoaded&&this.N(n.target,n.attributeName.substring(12)):s(n.target,n.attributeName,n.target.getAttribute(n.attributeName))),"childList"===n.type&&n.addedNodes.forEach(t=>{if(t.nodeType===Node.ELEMENT_NODE)if(this.everythingLoaded)for(const i of[t,...t.querySelectorAll(o)])for(const t of i.getAttribut

In [6]:
for h in soup.find_all(['h1','h2','h3']):
    print(h.get_text(strip=True))

Addis Insight
Why Addis Ababa’s Standard License Plates Are Now Among the World’s Costliest
Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion
Ethiopia’s New Vehicle Plates Roll Out With Fees of Up to 56,000 Birr
Stanbic’s Ethiopia Ambition Signals a New Phase in Africa’s Banking Race
IFC Approves $80M Loan to Upgrade Sheraton Addis and Build New Luxury Hotel
Why Addis Ababa’s Standard License Plates Are Now Among the World’s Costliest
Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion
Why Addis Ababa’s Standard License Plates Are Now Among the World’s Costliest
How Abel Tesfaye Became the World’s Highest-Paid Musician
Disconnected by Design: Why Christopher Nolan and Haile Gerima Reject the Smartphone
Politics
EU Revokes Strict Schengen Visa Rules for Ethiopian Nationals
Tigray’s Power Shift Explained: Debretsion’s Return and a Fragile Peace
When Strategic Restraint Is a Virtue: GERD, Nile Politics, and Trump Factor
Why Ethiopia Is Afraid of TikTokers
Business
Why Addis Ababa’s Standard License Plates Are Now Among the World’s Costliest
Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion
Ethiopia’s New Vehicle Plates Roll Out With Fees of Up to 56,000 Birr
Stanbic’s Ethiopia Ambition Signals a New Phase in Africa’s Banking Race
Market
Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion
Ethiopia’s New Vehicle Plates Roll Out With Fees of Up to 56,000 Birr
Stanbic’s Ethiopia Ambition Signals a New Phase in Africa’s Banking Race
IFC Approves $80M Loan to Upgrade Sheraton Addis and Build New Luxury Hotel
Entrepreneurship
Gursha launches Ethiopia’s first supermarket cash-back platform as digital payments hit an inflection point
Ethiopia’s Digital Creator Economy Gets a Boost as JAMI and Arifpay Launch Country’s First Multi-Currency Tipping Platform
Weyra Academy Launches 6-Week Web Development Course to Build Ethiopia’s Digital Workforce
Venture Meda: Job Creation through Incubation and acceleration in Ethiopia.
TECH
Code, Chalk, and National Pride: Inside Jelani Nelson’s Algorithmic Revolution
Digitizing end to end Procurement : Why Top Organizations are Turning to TenderSureTM ETHIOPIA
GuzoForex Bets on Ethiopia’s Youth With Gamified Trading Platform
Ethiopian Telemedicine Platform Tenadoc Brings Hospital OPD and International Second Opinions Online
Market
Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion
Ethiopia’s New Vehicle Plates Roll Out With Fees of Up to 56,000 Birr
Stanbic’s Ethiopia Ambition Signals a New Phase in Africa’s Banking Race
IFC Approves $80M Loan to Upgrade Sheraton Addis and Build New Luxury Hotel
Become a member
Music
How Abel Tesfaye Became the World’s Highest-Paid Musician
Federal High Court Grants Bail to Teddy Afro’s Assistant Manager and Co-Defendants
Teddy Afro’s 148 Million-View Triumph Highlights YouTube’s Ethiopia Revenue Problem
Teddy Afro’s Associates Arrested, Studio Raided After Etorika Album Breaks Records: What We Know
Movies
Disconnected by Design: Why Christopher Nolan and Haile Gerima Reject the Smartphone
Made in Ethiopia Earns Emmy Nomination, Spotlighting China’s Industrial Footprint Through Women’s Stories
Udet by Nobel & Tselimu: The Album That Refuses to Be Boxed
Beloved Ethiopian Actor and TV Host Netsanet Workneh Passes Away at 49
Books
Dinaw Mengestu Elected President of PEN America as Organization Faces Intensifying Free Speech Challenges
Why the Global Academy Is Turning to Ge’ez
Poet and Tobiya Jazz Event Organizer Misraq Terefe Arrested Amid Unclear Circumstances
Jawar Mohammed’s Memoir: “I Will Not Regret” – A Bold Reflection on Ethiopia’s Political...
Travel
Food & Drink
Ethiopia Unveils Landmark Shebele Resort in Push for Regional Tourism Hub
The Winners and Losers of Content Diplomacy: Inside IShowSpeed’s Africa Tour
Ethiopian Investment Holdings Drives $250 Million Flagship Hotel Push in Addis Ababa
MIDROC Investment Group Acquires Historic Wabi Shebele Hotel, Plans Marriott Autograph Collection Renovation
The Winners and Losers of Content Diplomacy: Inside IShowSpeed’s Africa Tour
MIDROC Investment Group Acquires Historic Wabi Shebele Hotel, Plans Marriott Autograph Collection Renovation
Bee’s Kitchen: A Thoughtfully Curated Newcomer Redefining Comfort Dining in Bole Medhanialem
Arabica Coffee Hits Record High, Signaling Global Market Shifts
Diaspora
Gebisa Ejeta Inducted Into U.S. Inventors Hall of Fame
How Bisaya Abdullahi Built Bisous Travel Into a Global Luxury Brand
TT Boys: Ethiopia’s Daring Acrobat Duo Who Took America’s Got Talent 2025 by Storm
Isak & Mulugheta: Eritrean Icons Driving Billion-Dollar Deals and Transfers
Who Told America That Ethiopia’s Sambusa Is an Appetizer?
Women
How Bisaya Abdullahi Built Bisous Travel Into a Global Luxury Brand
The Unequal Reality of Women’s Work in Ethiopia
The continued use of sexual violence as a weapon in Ethiopia: Public health and social crisis in the making
Creative DNA 3.0 Launches in Ethiopia, Showcasing the Next Wave of Fashion Innovators
Meet Emebet Mehabaw: Ethiopia’s First Woman Selected to Travel to Space in 2029
Subscribe

In [7]:
for a in soup.find_all("a", href=True):
    print(a.get("href"))

https://addisinsight.net/category/ethiopian-news/
https://addisinsight.net/politics/
https://addisinsight.net/business/
https://addisinsight.net/category/business/maret/
https://addisinsight.net/birr-exchange-rate/
https://addisinsight.net/category/entrepreneurship/
https://addisinsight.net/category/technology/
https://addisinsight.net/category/entertainment-and-arts/
https://addisinsight.net/category/entertainment-and-arts/ethiopian-movie/
https://addisinsight.net/category/entertainment-and-arts/ethiopian-books/
https://addisinsight.net/category/entertainment-and-arts/ethiopian-music/
https://addisinsight.net/category/culture/
https://addisinsight.net/category/culture/food-drink/
https://addisinsight.net/category/culture/history/
https://addisinsight.net/category/culture/travel/
https://addisinsight.net/category/health/
https://addisinsight.net/category/society/
https://addisinsight.net/category/diaspora/
https://addisinsight.net/category/women/
https://addisinsight.net/category/society/youth/
https://addisinsight.net/opinion/
https://addisinsight.net/category/sport/
https://addisinsight.net/exchange-rates/
https://addisinsight.net/birr-converter/
https://addisinsight.net/contact-us-2/
https://addisinsight.net/addis-insight-editorial-policy/
#
#
https://addisinsight.net/privacy-policy/
https://addisinsight.net/
#
https://addisinsight.net/
https://addisinsight.net/
https://addisinsight.net/category/ethiopian-news/
https://addisinsight.net/politics/
https://addisinsight.net/business/
https://addisinsight.net/category/business/maret/
https://addisinsight.net/birr-exchange-rate/
https://addisinsight.net/category/entrepreneurship/
https://addisinsight.net/category/technology/
https://addisinsight.net/category/entertainment-and-arts/
https://addisinsight.net/category/entertainment-and-arts/ethiopian-movie/
https://addisinsight.net/category/entertainment-and-arts/ethiopian-books/
https://addisinsight.net/category/entertainment-and-arts/ethiopian-music/
https://addisinsight.net/category/culture/
https://addisinsight.net/category/culture/food-drink/
https://addisinsight.net/category/culture/history/
https://addisinsight.net/category/culture/travel/
https://addisinsight.net/category/health/
https://addisinsight.net/category/society/
https://addisinsight.net/category/diaspora/
https://addisinsight.net/category/women/
https://addisinsight.net/category/society/youth/
https://addisinsight.net/opinion/
https://addisinsight.net/category/sport/
https://addisinsight.net/exchange-rates/
https://addisinsight.net/birr-converter/
https://addisinsight.net/contact-us-2/
https://addisinsight.net/addis-insight-editorial-policy/
#
#
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/2026/06/11/ethiopias-new-vehicle-plates-roll-out-with-fees-of-up-to-56000-birr/
https://addisinsight.net/2026/06/10/stanbics-ethiopia-ambition-signals-a-new-phase-in-africas-banking-race/
https://addisinsight.net/2026/06/10/ifc-approves-80m-loan-to-upgrade-sheraton-addis-and-build-new-luxury-hotel/
#
#
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/#respond
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/
https://addisinsight.net/2026/06/04/how-abel-tesfaye-became-the-worlds-highest-paid-musician/
https://addisinsight.net/category/entertainment-and-arts/
https://addisinsight.net/2026/06/04/how-abel-tesfaye-became-the-worlds-highest-paid-musician/
https://addisinsight.net/2026/05/22/disconnected-by-design-why-christopher-nolan-and-haile-gerima-reject-the-smartphone/
https://addisinsight.net/category/entertainment-and-arts/
https://addisinsight.net/2026/05/22/disconnected-by-design-why-christopher-nolan-and-haile-gerima-reject-the-smartphone/
#
https://addisinsight.net/2026/05/20/eu-revokes-strict-schengen-visa-rules-for-ethiopian-nationals/
https://addisinsight.net/category/politics/
https://addisinsight.net/2026/05/20/eu-revokes-strict-schengen-visa-rules-for-ethiopian-nationals/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/05/05/tigrays-power-shift-explained-debretsions-return-and-a-fragile-peace/
https://addisinsight.net/category/politics/
https://addisinsight.net/2026/05/05/tigrays-power-shift-explained-debretsions-return-and-a-fragile-peace/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/23/when-strategic-restraint-is-a-virtue-gerd-nile-politics-and-trump-factor/
https://addisinsight.net/category/opinion/
https://addisinsight.net/2026/01/23/when-strategic-restraint-is-a-virtue-gerd-nile-politics-and-trump-factor/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/12/26/why-ethiopia-is-afraid-of-tiktokers/
https://addisinsight.net/category/entertainment-and-arts/
https://addisinsight.net/2025/12/26/why-ethiopia-is-afraid-of-tiktokers/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/why-addis-ababas-standard-license-plates-are-now-among-the-worlds-costliest/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/11/ethiopias-new-vehicle-plates-roll-out-with-fees-of-up-to-56000-birr/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/ethiopias-new-vehicle-plates-roll-out-with-fees-of-up-to-56000-birr/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/10/stanbics-ethiopia-ambition-signals-a-new-phase-in-africas-banking-race/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/10/stanbics-ethiopia-ambition-signals-a-new-phase-in-africas-banking-race/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/11/ethiopias-new-vehicle-plates-roll-out-with-fees-of-up-to-56000-birr/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/ethiopias-new-vehicle-plates-roll-out-with-fees-of-up-to-56000-birr/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/10/stanbics-ethiopia-ambition-signals-a-new-phase-in-africas-banking-race/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/10/stanbics-ethiopia-ambition-signals-a-new-phase-in-africas-banking-race/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/10/ifc-approves-80m-loan-to-upgrade-sheraton-addis-and-build-new-luxury-hotel/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/10/ifc-approves-80m-loan-to-upgrade-sheraton-addis-and-build-new-luxury-hotel/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/12/19/gursha-launches-ethiopias-first-supermarket-cash-back-platform-as-digital-payments-hit-an-inflection-point/
https://addisinsight.net/category/business/
https://addisinsight.net/2025/12/19/gursha-launches-ethiopias-first-supermarket-cash-back-platform-as-digital-payments-hit-an-inflection-point/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/05/29/ethiopias-digital-creator-economy-gets-a-boost-as-jami-and-arifpay-launch-countrys-first-multi-currency-tipping-platform/
https://addisinsight.net/category/business/
https://addisinsight.net/2025/05/29/ethiopias-digital-creator-economy-gets-a-boost-as-jami-and-arifpay-launch-countrys-first-multi-currency-tipping-platform/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/04/25/weyra-academy-launches-6-week-web-development-course-to-build-ethiopias-digital-workforce/
https://addisinsight.net/category/entrepreneurship/
https://addisinsight.net/2025/04/25/weyra-academy-launches-6-week-web-development-course-to-build-ethiopias-digital-workforce/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/04/15/venture-meda-job-creation-through-incubation-and-acceleration-in-ethiopia/
https://addisinsight.net/category/business/
https://addisinsight.net/2025/04/15/venture-meda-job-creation-through-incubation-and-acceleration-in-ethiopia/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/05/29/code-chalk-and-national-pride-inside-jelani-nelsons-algorithmic-revolution/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/05/29/code-chalk-and-national-pride-inside-jelani-nelsons-algorithmic-revolution/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/04/08/digitizing-end-to-end-procurement-why-top-organizations-are-turning-to-tendersuretm-ethiopia/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/04/08/digitizing-end-to-end-procurement-why-top-organizations-are-turning-to-tendersuretm-ethiopia/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/04/07/guzoforex-bets-on-ethiopias-youth-with-gamified-trading-platform/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/04/07/guzoforex-bets-on-ethiopias-youth-with-gamified-trading-platform/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/03/30/ethiopian-telemedicine-platform-tenadoc-brings-hospital-opd-and-international-second-opinions-online/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/03/30/ethiopian-telemedicine-platform-tenadoc-brings-hospital-opd-and-international-second-opinions-online/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/11/ethiopias-new-vehicle-plates-roll-out-with-fees-of-up-to-56000-birr/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/11/ethiopias-new-vehicle-plates-roll-out-with-fees-of-up-to-56000-birr/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/10/stanbics-ethiopia-ambition-signals-a-new-phase-in-africas-banking-race/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/10/stanbics-ethiopia-ambition-signals-a-new-phase-in-africas-banking-race/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/10/ifc-approves-80m-loan-to-upgrade-sheraton-addis-and-build-new-luxury-hotel/
https://addisinsight.net/category/business/
https://addisinsight.net/2026/06/10/ifc-approves-80m-loan-to-upgrade-sheraton-addis-and-build-new-luxury-hotel/
https://addisinsight.net/author/admin/
#
https://addisinsight.net/2026/06/04/how-abel-tesfaye-became-the-worlds-highest-paid-musician/
https://addisinsight.net/2026/06/04/how-abel-tesfaye-became-the-worlds-highest-paid-musician/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/06/04/how-abel-tesfaye-became-the-worlds-highest-paid-musician/#respond
https://addisinsight.net/2026/05/20/federal-high-court-grants-bail-to-teddy-afros-assistant-manager-and-co-defendants/
https://addisinsight.net/2026/05/20/federal-high-court-grants-bail-to-teddy-afros-assistant-manager-and-co-defendants/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/05/20/federal-high-court-grants-bail-to-teddy-afros-assistant-manager-and-co-defendants/#respond
https://addisinsight.net/2026/05/14/teddy-afros-148-million-view-triumph-highlights-youtubes-ethiopia-revenue-problem/
https://addisinsight.net/2026/05/14/teddy-afros-148-million-view-triumph-highlights-youtubes-ethiopia-revenue-problem/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/05/14/teddy-afros-148-million-view-triumph-highlights-youtubes-ethiopia-revenue-problem/#respond
https://addisinsight.net/2026/05/04/teddy-afros-associates-arrested-studio-raided-after-etorika-album-breaks-records-what-we-know/
https://addisinsight.net/2026/05/04/teddy-afros-associates-arrested-studio-raided-after-etorika-album-breaks-records-what-we-know/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/05/04/teddy-afros-associates-arrested-studio-raided-after-etorika-album-breaks-records-what-we-know/#respond
#
#
https://addisinsight.net/2026/05/22/disconnected-by-design-why-christopher-nolan-and-haile-gerima-reject-the-smartphone/
https://addisinsight.net/2026/05/22/disconnected-by-design-why-christopher-nolan-and-haile-gerima-reject-the-smartphone/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/05/22/disconnected-by-design-why-christopher-nolan-and-haile-gerima-reject-the-smartphone/#respond
https://addisinsight.net/2026/05/03/made-in-ethiopia-earns-emmy-nomination-spotlighting-chinas-industrial-footprint-through-womens-stories/
https://addisinsight.net/2026/05/03/made-in-ethiopia-earns-emmy-nomination-spotlighting-chinas-industrial-footprint-through-womens-stories/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/05/03/made-in-ethiopia-earns-emmy-nomination-spotlighting-chinas-industrial-footprint-through-womens-stories/#respond
https://addisinsight.net/2026/01/20/udet-by-nobel-tselimu-the-album-that-refuses-to-be-boxed/
https://addisinsight.net/2026/01/20/udet-by-nobel-tselimu-the-album-that-refuses-to-be-boxed/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/20/udet-by-nobel-tselimu-the-album-that-refuses-to-be-boxed/#respond
https://addisinsight.net/2026/01/16/beloved-ethiopian-actor-and-tv-host-netsanet-workneh-passes-away-at-49/
https://addisinsight.net/2026/01/16/beloved-ethiopian-actor-and-tv-host-netsanet-workneh-passes-away-at-49/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/16/beloved-ethiopian-actor-and-tv-host-netsanet-workneh-passes-away-at-49/#respond
#
#
https://addisinsight.net/2025/12/23/dinaw-mengestu-elected-president-of-pen-america-as-organization-faces-intensifying-free-speech-challenges/
https://addisinsight.net/2025/12/23/dinaw-mengestu-elected-president-of-pen-america-as-organization-faces-intensifying-free-speech-challenges/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/12/23/dinaw-mengestu-elected-president-of-pen-america-as-organization-faces-intensifying-free-speech-challenges/#respond
https://addisinsight.net/2025/09/17/why-the-global-academy-is-turning-to-geez/
https://addisinsight.net/2025/09/17/why-the-global-academy-is-turning-to-geez/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/09/17/why-the-global-academy-is-turning-to-geez/#respond
https://addisinsight.net/2025/02/01/poet-and-tobiya-jazz-event-organizer-misraq-terefe-arrested-amid-unclear-circumstances/
https://addisinsight.net/2025/02/01/poet-and-tobiya-jazz-event-organizer-misraq-terefe-arrested-amid-unclear-circumstances/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/02/01/poet-and-tobiya-jazz-event-organizer-misraq-terefe-arrested-amid-unclear-circumstances/#respond
https://addisinsight.net/2024/12/14/jawar-mohammeds-memoir-i-will-not-regret-a-bold-reflection-on-ethiopias-political-struggles/
https://addisinsight.net/2024/12/14/jawar-mohammeds-memoir-i-will-not-regret-a-bold-reflection-on-ethiopias-political-struggles/
https://addisinsight.net/author/admin/
https://addisinsight.net/2024/12/14/jawar-mohammeds-memoir-i-will-not-regret-a-bold-reflection-on-ethiopias-political-struggles/#comments
#
#
https://addisinsight.net/2026/01/31/ethiopia-unveils-landmark-shebele-resort-in-push-for-regional-tourism-hub/
https://addisinsight.net/2026/01/31/ethiopia-unveils-landmark-shebele-resort-in-push-for-regional-tourism-hub/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/31/ethiopia-unveils-landmark-shebele-resort-in-push-for-regional-tourism-hub/#respond
https://addisinsight.net/2026/01/28/the-winners-and-losers-of-content-diplomacy-inside-ishowspeeds-africa-tour/
https://addisinsight.net/2026/01/28/the-winners-and-losers-of-content-diplomacy-inside-ishowspeeds-africa-tour/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/28/the-winners-and-losers-of-content-diplomacy-inside-ishowspeeds-africa-tour/#respond
https://addisinsight.net/2026/01/22/ethiopian-investment-holdings-drives-250-million-flagship-hotel-push-in-addis-ababa/
https://addisinsight.net/2026/01/22/ethiopian-investment-holdings-drives-250-million-flagship-hotel-push-in-addis-ababa/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/22/ethiopian-investment-holdings-drives-250-million-flagship-hotel-push-in-addis-ababa/#respond
https://addisinsight.net/2026/01/21/midroc-investment-group-acquires-historic-wabi-shebele-hotel-plans-marriott-autograph-collection-renovation/
https://addisinsight.net/2026/01/21/midroc-investment-group-acquires-historic-wabi-shebele-hotel-plans-marriott-autograph-collection-renovation/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/21/midroc-investment-group-acquires-historic-wabi-shebele-hotel-plans-marriott-autograph-collection-renovation/#respond
https://addisinsight.net/2026/01/28/the-winners-and-losers-of-content-diplomacy-inside-ishowspeeds-africa-tour/
https://addisinsight.net/2026/01/28/the-winners-and-losers-of-content-diplomacy-inside-ishowspeeds-africa-tour/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/28/the-winners-and-losers-of-content-diplomacy-inside-ishowspeeds-africa-tour/#respond
https://addisinsight.net/2026/01/21/midroc-investment-group-acquires-historic-wabi-shebele-hotel-plans-marriott-autograph-collection-renovation/
https://addisinsight.net/2026/01/21/midroc-investment-group-acquires-historic-wabi-shebele-hotel-plans-marriott-autograph-collection-renovation/
https://addisinsight.net/author/admin/
https://addisinsight.net/2026/01/21/midroc-investment-group-acquires-historic-wabi-shebele-hotel-plans-marriott-autograph-collection-renovation/#respond
https://addisinsight.net/2025/12/23/bees-kitchen-a-thoughtfully-curated-newcomer-redefining-comfort-dining-in-bole-medhanialem/
https://addisinsight.net/2025/12/23/bees-kitchen-a-thoughtfully-curated-newcomer-redefining-comfort-dining-in-bole-medhanialem/
https://addisinsight.net/author/admin/
https://addisinsight.net/2025/12/23/bees-kitchen-a-thoughtfully-curated-newcomer-redefining-comfort-dining-in-bole-medhanialem/#respond

In [8]:
titles = []

for tag in soup.find_all(['h1','h2','h3']):
    text = tag.get_text(strip=True)

    if len(text) > 20:
        titles.append(text)

titles[:20]

['Why Addis Ababa’s Standard License Plates Are Now Among the World’s Costliest',
 'Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion',
 'Ethiopia’s New Vehicle Plates Roll Out With Fees of Up to 56,000 Birr',
 'Stanbic’s Ethiopia Ambition Signals a New Phase in Africa’s Banking Race',
 'IFC Approves $80M Loan to Upgrade Sheraton Addis and Build New Luxury Hotel',
 'Why Addis Ababa’s Standard License Plates Are Now Among the World’s Costliest',
 'Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion',
 'Why Addis Ababa’s Standard License Plates Are Now Among the World’s Costliest',
 'How Abel Tesfaye Became the World’s Highest-Paid Musician',
 'Disconnected by Design: Why Christopher Nolan and Haile Gerima Reject the Smartphone',
 'EU Revokes Strict Schengen Visa Rules for Ethiopian Nationals',
 'Tigray’s Power Shift Explained: Debretsion’s Return and a Fragile Peace',
 'When Strategic Restraint Is a Virtue: GERD, Nile Politics, and Trump Factor',
 'Why Ethiopia Is Afraid of TikTokers',
 'Why Addis Ababa’s Standard License Plates Are Now Among the World’s Costliest',
 'Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion',
 'Ethiopia’s New Vehicle Plates Roll Out With Fees of Up to 56,000 Birr',
 'Stanbic’s Ethiopia Ambition Signals a New Phase in Africa’s Banking Race',
 'Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion',
 'Ethiopia’s New Vehicle Plates Roll Out With Fees of Up to 56,000 Birr']

In [53]:
data = []

for h in soup.find_all(['h2','h3']):
    a = h.find("a")

    if a:
        title = a.get_text(strip=True)
        link = a.get("href")

        data.append({
            "title": title,
            "link": link
        })

data[:10]

[{'title': 'Girma Wake Leads Uganda Airlines Into $982 Million Boeing Fleet Expansion',
  'link': 'https://addisinsight.net/2026/06/11/girma-wake-leads-uganda-airlines-into-982-million-boeing-fleet-expansion/'},
 {'title': 'Ethiopia’s New Vehicle Plates Roll Out With Fees of Up to 56,000 Birr',
  'link': 'https://addisinsight.net/2026/06/11/ethiopias-new-vehicle-plates-roll-out-with-fees-of-up-to-56000-birr/'},
 {'title': 'Stanbic’s Ethiopia Ambition Signals a New Phase in Africa’s Banking Race',
  'link': 'https://addisinsight.net/2026/06/10/stanbics-ethiopia-ambition-signals-a-new-phase-in-africas-banking-race/'},
 {'title': 'IFC Approves $80M Loan to Upgrade Sheraton Addis and Build New Luxury Hotel',
  'link': 'https://addisinsight.net/2026/06/10/ifc-approves-80m-loan-to-upgrade-sheraton-addis-and-build-new-luxury-hotel/'}]

In [32]:
import pandas as pd
import csv
import pandas as pd
df = pd.DataFrame(data)
df.head()

,title,link
0,Why Addis Ababa’s Standard License Plates Are ...,https://addisinsight.net/2026/06/11/why-addis-...
1,Girma Wake Leads Uganda Airlines Into $982 Mil...,https://addisinsight.net/2026/06/11/girma-wake...
2,Ethiopia’s New Vehicle Plates Roll Out With Fe...,https://addisinsight.net/2026/06/11/ethiopias-...
3,Stanbic’s Ethiopia Ambition Signals a New Phas...,https://addisinsight.net/2026/06/10/stanbics-e...
4,IFC Approves $80M Loan to Upgrade Sheraton Add...,https://addisinsight.net/2026/06/10/ifc-approv...

In [54]:
df.to_csv("addis_insight_articles.csv", index=False)

In [39]:
title = article_soup.find("h2")
print(title.text.strip())

Part I: The Anatomy of a Tech Upgrade

In [40]:
paragraphs = article_soup.find_all("p")

content = " ".join(
    p.get_text(strip=True)
    for p in paragraphs
)

print(content[:1000])

Date: Share post: For decades, the global narrative surrounding multi-thousand-dollar license plates belonged exclusively to the luxury markets of the Gulf Cooperation Council (GCC) states. High-profile vanity auctions in Dubai, Abu Dhabi, or Doha—where single-digit plates regularly clear millions of dollars for charity—firmly established vehicle registration as a playground for billionaires. However, a massive policy shift in East Africa has flipped that script entirely. With the official rollout of the new standardized national vehicle license plates underDirective No. 1050/2025, theAddis Ababa Drivers and Vehicles Licensing and Control Authorityhas introduced a mandatory tariff structure that places Ethiopia at the very top of global rankings for the baseline cost of regular, standard vehicle registration. At56,000 ETB (~$460–$470 USD)for a standard private fuel-powered car, a regular, sequential vehicle plate in Addis Ababa now costs significantly more than in the United States, We

In [38]:
articles = []

for a in soup.select("a[href]"):
    title = a.get_text(strip=True)
    link = a["href"]

    if len(title) > 30:
        articles.append([title, link])

df = pd.DataFrame(articles, columns=["Title", "Link"])
df.drop_duplicates(inplace=True)

df.head()

,Title,Link
0,Why Addis Ababa’s Standard License Plates Are ...,https://addisinsight.net/2026/06/11/why-addis-...
1,Girma Wake Leads Uganda Airlines Into $982 Mil...,https://addisinsight.net/2026/06/11/girma-wake...
2,Ethiopia’s New Vehicle Plates Roll Out With Fe...,https://addisinsight.net/2026/06/11/ethiopias-...
3,Stanbic’s Ethiopia Ambition Signals a New Phas...,https://addisinsight.net/2026/06/10/stanbics-e...
4,IFC Approves $80M Loan to Upgrade Sheraton Add...,https://addisinsight.net/2026/06/10/ifc-approv...

In [41]:
pd.read_csv("addis_insight_articles.csv")

,title,link
0,Why Addis Ababa’s Standard License Plates Are ...,https://addisinsight.net/2026/06/11/why-addis-...
1,Girma Wake Leads Uganda Airlines Into $982 Mil...,https://addisinsight.net/2026/06/11/girma-wake...
2,Ethiopia’s New Vehicle Plates Roll Out With Fe...,https://addisinsight.net/2026/06/11/ethiopias-...
3,Stanbic’s Ethiopia Ambition Signals a New Phas...,https://addisinsight.net/2026/06/10/stanbics-e...
4,IFC Approves $80M Loan to Upgrade Sheraton Add...,https://addisinsight.net/2026/06/10/ifc-approv...
...,...,...
59,How Bisaya Abdullahi Built Bisous Travel Into ...,https://addisinsight.net/2026/05/07/how-bisaya...
60,The Unequal Reality of Women’s Work in Ethiopia,https://addisinsight.net/2026/04/23/the-unequa...
61,The continued use of sexual violence as a weap...,https://addisinsight.net/2026/04/15/the-contin...
62,"Creative DNA 3.0 Launches in Ethiopia, Showcas...",https://addisinsight.net/2025/09/20/creative-d...
63,Meet Emebet Mehabaw: Ethiopia’s First Woman Se...,https://addisinsight.net/2025/09/10/meet-emebe...

In [55]:
import pandas as pd

df = pd.read_csv("addis_insight_articles.csv")
print(df.head())

                                               title  \
0  Why Addis Ababa’s Standard License Plates Are ...
1  Girma Wake Leads Uganda Airlines Into $982 Mil...
2  Ethiopia’s New Vehicle Plates Roll Out With Fe...
3  Stanbic’s Ethiopia Ambition Signals a New Phas...
4  IFC Approves $80M Loan to Upgrade Sheraton Add...

                                                link  category
0  https://addisinsight.net/2026/06/11/why-addis-...       NaN
1  https://addisinsight.net/2026/06/11/girma-wake...       NaN
2  https://addisinsight.net/2026/06/11/ethiopias-...       NaN
3  https://addisinsight.net/2026/06/10/stanbics-e...       NaN
4  https://addisinsight.net/2026/06/10/ifc-approv...       NaN